# Generated by Django 4.0.4 on 2022-05-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_courses_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='images/courses/default.png', upload_to='images/courses/%Y/%m/%d/'),
        ),
    ]
