# Generated by Django 4.0.4 on 2022-05-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=0, help_text='Öğretmen adı giriniz', max_length=30, null=0, verbose_name='Öğretmen Adı')),
                ('lastName', models.CharField(blank=0, help_text='Öğretmen soyadı giriniz', max_length=30, null=0, verbose_name='Öğretmen Soyadı')),
                ('jobTitle', models.CharField(blank=0, help_text='Öğretmen alanı giriniz', max_length=45, null=0, verbose_name='Öğretmen Alanı')),
                ('image', models.ImageField(default='uploads/teachers/default.png', upload_to='uploads/teachers/%Y/%m/%d/')),
                ('registerDate', models.DateTimeField(auto_now=True)),
                ('facebook', models.CharField(blank=True, help_text='Facebook adresi giriniz', max_length=70, null=True, verbose_name='Facebook')),
                ('linkedIn', models.CharField(blank=True, help_text='LinkedIn adresi giriniz', max_length=70, null=True, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, help_text='Twitter adresi giriniz', max_length=70, null=True, verbose_name='Facebook')),
                ('skype', models.CharField(blank=True, help_text='Facebook adresi giriniz', max_length=70, null=True, verbose_name='Facebook')),
            ],
        ),
    ]
