# Generated by Django 4.0.4 on 2022-06-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='linkedIn',
            field=models.CharField(blank=True, help_text='LinkedIn adresi giriniz', max_length=70, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='skype',
            field=models.CharField(blank=True, help_text='Facebook adresi giriniz', max_length=70, null=True, verbose_name='Skype'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='twitter',
            field=models.CharField(blank=True, help_text='Twitter adresi giriniz', max_length=70, null=True, verbose_name='Twitter'),
        ),
    ]
